extern int w;//кол-во столбцов
extern int l;//кол-во строк
void decodeStep1(char **content) {}
void decodeStep2(char **content) {}
void decodeStep3(char **content) {}
void decodeStep4(char **content) {}
void decodeStep5(char **content) {}
void decodeStep6(char **content) {}
void decodeStep7(char **content) {}
void decodeStep8(char **content) {}
void decodeStep9(char **content) {}
